export const storeItems = [
    { id: 1, name: "Smartphone", price: 599, image: "/phone.png" },
    { id: 2, name: "Laptop", price: 999, image: "/laptop.png" },
    { id: 3, name: "Headphones", price: 199, image: "/headphones.png" },
    { id: 4, name: "Smartwatch", price: 299, image: "/smartwatch.png" },
    { id: 5, name: "Tablet", price: 449, image: "/tablet.png" },
    { id: 6, name: "Camera", price: 799, image: "/camera.png" },
    { id: 7, name: "Gaming Console", price: 499, image: "/gamingconsole.png" },
    { id: 8, name: "Wireless Earbuds", price: 159, image: "/airbuds.png" },
    { id: 9, name: "Smart Speaker", price: 99, image: "/smartspeaker.png" },
    { id: 10, name: "Fitness Tracker", price: 129, image: "/fitnesstracker.png" },
    { id: 11, name: "External Hard Drive", price: 89, image: "/harddrive.png" },
    { id: 12, name: "Wireless Mouse", price: 39, image: "/wirelessmouse.png" },
    { id: 13, name: "Portable Charger", price: 49, image: "/portablecharger.png" },
    { id: 14, name: "Bluetooth Speaker", price: 79, image: "/bluetoothspeaker.png" },
    { id: 15, name: "Graphic Tablet", price: 249, image: "/graphicstablet.png" },
    { id: 16, name: "Webcam", price: 69, image: "/webcam.png" },
    { id: 17, name: "Mechanical Keyboard", price: 129, image: "/mechanicalkeyboard.png" },
    { id: 18, name: "Monitor", price: 349, image: "/monitor.png" },
    { id: 19, name: "Router", price: 89, image: "/router.png" },
    { id: 20, name: "VR Headset", price: 399, image: "/vrheadset.png" },
    { id: 21, name: "Drone", price: 599, image: "/drone.png" },
    { id: 22, name: "Smart Thermostat", price: 179, image: "/smartthermostat.png" },
    { id: 23, name: "Electric Scooter", price: 399, image: "/electricscooter.png" },
    { id: 24, name: "Wireless Printer", price: 199, image: "/wirelessprinter.png" },
    { id: 25, name: "Smart Lock", price: 149, image: "/smartlock.png" },
    { id: 26, name: "Smart TV", price: 149, image: "/smarttv.png" },
    { id: 27, name: "Laptop Sleeve", price: 29, image: "/laptopsleeve.png" },
    { id: 28, name: "Car Charger", price: 19, image: "/carcharger.png" },
    { id: 29, name: "Action Camera", price: 129, image: "/actioncamera.png" },
    { id: 30, name: "LED Desk Lamp", price: 39, image: "/desklamp.png" },
    { id: 31, name: "Smart Light Bulb", price: 25, image: "/lightbulb.png" },
    { id: 32, name: "E-Reader", price: 129, image: "/ereader.png" },
    { id: 33, name: "Keyboard Cover", price: 9, image: "/keyboardcover.png" },
    { id: 34, name: "Phone Case", price: 19, image: "/phonecase.png" },
    { id: 35, name: "Fitness Mat", price: 49, image: "/fitnessmat.png" },
    { id: 36, name: "Portable Speaker", price: 59, image: "/portablespeaker.png" },
    { id: 37, name: "Wireless Charging Pad", price: 29, image: "/chargingpad.png" },
    { id: 38, name: "Smart Ring", price: 99, image: "/smartring.png" },
    { id: 39, name: "Mini Fridge", price: 199, image: "/minifridge.png" },
    { id: 40, name: "Smart Lamp", price: 69, image: "/smartlamp.png" }
];
